version: '3.4'

services:
  reverseproxy:
    image: dockertest_reversproxy
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "44344:443"
    restart: always
    depends_on:
      - docker.test.webapi
  docker.test.webapi:
    build:
      context: .
      dockerfile: docker.test.webapi/Dockerfile
    ports:
      - "8080:80"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
    restart: always
  seqservice:
    image: datalust/seq
    restart: unless-stopped
    ports:
      - "5341:80"
    environment:
      - "ACCEPT_EULA=Y"
  sqlserver: 
    image: mcr.microsoft.com/mssql/server
    restart: always
    ports:
      - "1434:1433"
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=1StrongPwd!!"